In [19]:
import numpy as np
import pandas as pd

In [20]:
flats = pd.read_csv('../data/processed/flats_cleaned.csv')
houses = pd.read_csv('../data/processed/house_cleaned.csv')

In [21]:
flats.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,2 BHK Flat in Krishna Colony,flat,maa bhagwati residency,0.45,5000.0,900.0,Carpet area: 900 (83.61 sq.m.),2,2,1,not available,"Krishna Colony, Gurgaon, Haryana",4.0,West,1 to 5 Year Old,"['Chintapurni Mandir', 'State bank ATM', 'Pear...",So with lift.Maa bhagwati residency is one of ...,"['3 Fan', '4 Light', '1 Wardrobe', 'No AC', 'N...","['Feng Shui / Vaastu Compliant', 'Security / F...","['Environment4 out of 5', 'Safety4 out of 5', ..."
1,2 BHK Flat in Ashok Vihar,flat,apna enclave,0.50,7692.0,650.0,Carpet area: 650 (60.39 sq.m.),2,2,1,not available,"46b, Ashok Vihar, Gurgaon, Haryana",1.0,West,10+ Year Old,"['Chintapurni Mandir', 'Sheetla Mata Mandir', ...","Property situated on main road, railway statio...","['3 Wardrobe', '4 Fan', '1 Exhaust Fan', '1 Ge...","['Security / Fire Alarm', 'Maintenance Staff',...","['Environment4 out of 5', 'Safety4 out of 5', ..."
2,2 BHK Flat in Sohna,flat,tulsiani easy in homes,0.40,6722.0,595.0,Carpet area: 595 (55.28 sq.m.),2,2,3,not available,"Sohna, Gurgaon, Haryana",12.0,NaN,0 to 1 Year Old,"['Huda City Metro', 'Golf Course extn road', '...","This property is 15 km away from badshapur, gu...",NaN,"['Power Back-up', 'Feng Shui / Vaastu Complian...","['Environment4 out of 5', 'Safety4 out of 5', ..."
3,2 BHK Flat in Sector 61 Gurgaon,flat,smart world orchard,1.47,12250.0,1200.0,Carpet area: 1200 (111.48 sq.m.),2,2,2,study room,"Sector 61 Gurgaon, Gurgaon, Haryana",2.0,NaN,Dec 2023,"['Sector 55-56 Metro station', 'Bestech Centra...",Near to metro station of sector 56 and opposit...,NaN,"['Security / Fire Alarm', 'Private Garden / Te...",NaN
4,2 BHK Flat in Sector 92 Gurgaon,flat,parkwood westend,0.70,5204.0,1345.0,Super Built up area 1345(124.95 sq.m.),2,2,3,study room,"Sector 92 Gurgaon, Gurgaon, Haryana",5.0,NaN,Under Construction,"['Yadav Clinic', 'Bangali Clinic', 'Dr. J. S. ...",We are the proud owners of this 2 bhk alongwit...,[],NaN,"['Environment5 out of 5', 'Safety3 out of 5', ..."

In [22]:
houses.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,5 Bedroom House for sale in Sector 70A Gurgaon,house,bptp visionnaire,5.25,20115.0,2610.0,Plot area 290(242.48 sq.m.),5,4,3+,servant room,"29b, Sector 70A Gurgaon, Gurgaon, Haryana",3.0,North-East,0 to 1 Year Old,"['Good Earth City Center 2', 'Kunskapsskolan I...",Do you wish to buy an independent house in sec...,"['1 Wardrobe', '1 Fan', '1 Exhaust Fan', '1 Ge...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
1,5 Bedroom House for sale in Sector 21A Faridabad,house,independent,5.70,105751.0,539.0,Plot area 539(50.07 sq.m.),5,4,2,"store room,pooja room,servant room","Sector 21A Faridabad, Gurgaon, Haryana",2.0,NaN,5 to 10 Year Old,NaN,"Hi, we have an independent house/villa availab...","['1 Water Purifier', '5 Fan', '1 Exhaust Fan',...","['Private Garden / Terrace', 'Park', 'Visitor ...",NaN
2,10 Bedroom House for sale in Sushant Lok Phase 1,house,independent,2.10,38251.0,549.0,Plot area 61(51 sq.m.),10,10,3+,servant room,"Sushant Lok Phase 1, Gurgaon, Haryana",5.0,West,0 to 1 Year Old,"['Sector 42-43 metro station', 'Huda city cent...","Monthly rental income is rs1,40,000/- Best opt...","['10 Bed', '3 Fan', '10 Geyser', '2 Light', 'N...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."
3,21 Bedroom House for sale in Sector 54 Gurgaon,house,independent,5.00,43066.0,1161.0,Plot area 129(107.86 sq.m.),21,21,3+,servant room,"Sector 54 Gurgaon, Gurgaon, Haryana",5.0,North,1 to 5 Year Old,"['Sector 53-54 metro station', 'Sector 54 chow...","129 sq yd plot size. 5 floors built up , fully...","['1 Water Purifier', '21 Fan', '1 Fridge', '1 ...","['Feng Shui / Vaastu Compliant', 'Private Gard...","['Environment4 out of 5', 'Lifestyle5 out of 5..."
4,12 Bedroom House for sale in Sushant Lok Phase 1,house,independent,3.00,53763.0,558.0,Plot area 62(51.84 sq.m.),12,12,3+,others,"1228, Sushant Lok Phase 1, Gurgaon, Haryana",5.0,West,Within 6 months,"['Sector 42-43 metro station', 'Huda city cent...",Best for investment purpose. Fully furnished b...,"['1 Water Purifier', '1 Fridge', '12 Fan', '1 ...","['Maintenance Staff', 'Water Storage', 'Visito...","['Environment5 out of 5', 'Lifestyle5 out of 5..."

In [23]:
df = pd.concat([flats,houses],ignore_index=True)

In [24]:
df = df.sample(df.shape[0],ignore_index=True)

In [25]:
df.head()

,property_name,property_type,society,price,price_per_sqft,area,areaWithType,bedRoom,bathroom,balcony,additionalRoom,address,floorNum,facing,agePossession,nearbyLocations,description,furnishDetails,features,rating
0,4 BHK Flat in Sector 1 Imt Manesar,flat,hsiidc sidco aravali,0.90,3648.0,2467.0,Super Built up area 2467(229.19 sq.m.),4,4,3,not available,"Sector 1 Imt Manesar, Gurgaon, Haryana",7.0,NaN,5 to 10 Year Old,"['Pooja Clinic', 'Dr. Sahil Clinic', 'Prakash ...",We are the proud owners of this 4 bhk apartmen...,[],NaN,"['Environment5 out of 5', 'Safety4.5 out of 5'..."
1,2 BHK Flat in Sector 70A Gurgaon,flat,capital residences 360,1.10,7586.0,1450.0,Super Built up area 1450(134.71 sq.m.),2,2,3+,not available,"Sector 70A Gurgaon, Gurgaon, Haryana",8.0,NaN,0 to 1 Year Old,NaN,"Address: 1st floor, sector 70a gurgaon, gurgao...","['2 Geyser', '3 AC', 'No Bed', 'No Chimney', '...","['Intercom Facility', 'Lift(s)', 'Maintenance ...","['Environment5 out of 5', 'Lifestyle4 out of 5..."
2,2 BHK Flat in Sector 88A Gurgaon,flat,godrej oasis,1.00,6896.0,1450.0,Carpet area: 1450 (134.71 sq.m.),2,2,3,study room,"Sector 88A Gurgaon, Gurgaon, Haryana",7.0,NaN,1 to 5 Year Old,"['Double Infinity market', 'Pataudi road', 'Dw...",This beautiful 2 bhk flat in sector-88a gurgao...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'Fe...","['Green Area5 out of 5', 'Construction4.5 out ..."
3,2 BHK Flat in Sector 86 Gurgaon,flat,pyramid elite,0.45,7739.0,581.0,Carpet area: 581.41 (54.01 sq.m.),2,2,1,not available,"Tower 2 Floor 4th, Sector 86 Gurgaon, Gurgaon,...",4.0,NaN,Nov 2023,"['V3S Sapphire Ninety Mall', 'Sector 86 Road',...",This lovely 2 bhk apartment/flat in sector 86 ...,NaN,"['Security / Fire Alarm', 'Power Back-up', 'In...","['Environment5 out of 5', 'Safety4.5 out of 5'..."
4,4 Bedroom House for sale in Sector 26 Gurgaon,house,independent,5.80,12837.0,4518.0,Plot area 502(419.74 sq.m.),4,4,3+,not available,"G-7/6, Sector 26 Gurgaon, Gurgaon, Haryana",4.0,NaN,10+ Year Old,"['Guru dronacharya metro station', 'Sikandarpu...",Sector 26 gurgaon is one of gurgaon's most sou...,[],"['Private Garden / Terrace', 'Maintenance Staf...",NaN

In [26]:

# Import Path class
from pathlib import Path
 
# Path
path = '../data/processed/gurgaon_properties.csv'
 
# Instantiate the Path class
obj = Path(path)
 
# Check if path points to
# an existing file or directory
# print(obj.exists())
if ~obj.exists():
    df.to_csv(path,index=False)

In [27]:
df['property_type'].value_counts()

property_type
flat     2996
house     964
Name: count, dtype: int64